version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: jobeet-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=admin
        - MYSQL_DATABASE=jobeet
        - MYSQL_USER=root
        - MYSQL_PASSWORD=admin
      ports:
        - "8081:3306"

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: jobeet-phpmyadmin
      links:
        - mysql
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
      ports:
        - '8082:80'

    webserver:
      image: nginx:alpine
      container_name: jobeet-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8080:80"

    php-fpm:
      build: docker/php-fpm
      container_name: jobeet-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

